apiVersion: v1
kind: Service
metadata:
  name: demo-lb-nos-svc
  labels:
    app: webapp1-loadbalancer
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: http-server-with-lb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-server-with-lb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-server-with-lb
  template:
    metadata:
      labels:
        app: http-server-with-lb
    spec:
      containers:
      - name: http-server
        image: katacoda/docker-http-server
        ports:
        - containerPort: 80