apiVersion: v1
kind: Service
metadata:
  name: d2-lb-web-app
  labels:
    app: webapp1-loadbalancer
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: http-server-with-lb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-server-with-lb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: http-server-with-lb
  template:
    metadata:
      labels:
        app: http-server-with-lb
    spec:
      containers:
      - name: http-server
        image: katacoda/docker-http-server
        ports:
        - containerPort: 80
      nodeSelector:
        kubernetes.io/role: agent
        beta.kubernetes.io/os: linux
        type: virtual-kubelet
      tolerations:
      - key: virtual-kubelet.io/provider
        operator: Exists
      - key: azure.com/aci
        effect: NoSchedule
      - key: use
        operator: Exists
        effect: NoSchedule