apiVersion: v1
kind: Service
metadata:
  name: demo-lb-nos-svc
  labels:
    app: webapp1-loadbalancer
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: aci-helloworld-with-lb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aci-helloworld-with-lb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aci-helloworld-with-lb
  template:
    metadata:
      labels:
        app: aci-helloworld-with-lb
    spec:
      containers:
      - name: aci-helloworld
        image: katacoda/docker-http-server
        ports:
        - containerPort: 80